Migration to gold
bcgov/lucy-web pull request #1132
Opened 2023-05-11 19:19 UTC by Christopher-walsh22

Testing works locally. Moving to dev for initial round.

2023-05-11 20:29 UTC, davidclaveau submitted a review, later dismissed

2023-05-11 20:32 UTC, TimCsaky commented
wondering if you need to update some of the SSO related values in the openshift templates in `api/openshift` and `app/openshift`

2023-05-11 21:09 UTC, davidclaveau commented on .config/config.json
> +            "url": "https://test.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/certs",
Looks like additional paths added. I think these need to be just "https://test.loginproxy.gov.bc.ca"

2023-05-11 21:09 UTC, davidclaveau commented on .config/config.json
> +            "url": "https://loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/certs",
Same as above, just "https://loginproxy.gov.bc.ca"

2023-05-11 21:11 UTC, davidclaveau requested changes
Just minor change to the url in the config.json file

2023-05-11 21:13 UTC, davidclaveau approved these changes, later dismissed

2023-05-11 21:47 UTC, davidclaveau submitted a review, later dismissed

2023-05-12 16:44 UTC, davidclaveau approved these changes

2023-05-12 16:45 UTC, merged